### ISSUE TITLE
Login page shows 404 error

### ISSUE THREAD

**Issue by jorgesat** [YunoHost-Apps/lemmy_ynh#17]
### Describe the bug

A fresh install of the app cannot be accessed by the admin account. 
The login page shows a 404 error message: 
`404 Code: TypeError: Cannot read property 'site' of undefined`

When the root domain is accesed (installation domain), the Lemmy Instance Setup is shown asking to create a new admin account. Once created, the account is not allowed to setup the instance because it is not ad admin account.

### Context

- Hardware: VPS bought online 
- YunoHost version: 4.3.6.2
- I have access to my server: Through SSH | through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 
- Using, or trying to install package version/branch: 0.15.2

### Steps to reproduce

Install lemmy app, try to set up the instance.

### Expected behavior

The instance should be setup by the admin user chosen in the installation process.

**Comment by jhammons** [comment]
I believe this will be fixed by https://github.com/YunoHost-Apps/lemmy_ynh/pull/20 ...

**Comment by Folaht** [comment]
This bug has come back.  

https://forum.yunohost.org/t/initial-lemmy-setup-fails/20713/5

**Comment by minnixtx** [comment]
I can confirm am having the exact same problem.

**Comment by yalh76** [comment]
Just tested on a fresh YunoHost, and it's working from my side.

Can you provide some logs like:
- `journalctl -feu lemmy`
- `journalctl -feu lemmy-ui`
- `/var/log/lemmy/lemmy.log`
- `/var/log/lemmy/lemmy-ui.log`

**Comment by Tuxi2020** [comment]
Same issue here.

journalctl -feu lemmy
-- Journal begins at Sat 2022-07-30 22:07:20 CEST. --
Sep 24 12:50:55 metaversum.wtf systemd[1]: Started lemmy Lemmy Daemon.
Sep 24 13:14:52 metaversum.wtf systemd[1]: Stopping lemmy Lemmy Daemon...
Sep 24 13:14:59 metaversum.wtf systemd[1]: lemmy.service: Succeeded.
Sep 24 13:14:59 metaversum.wtf systemd[1]: Stopped lemmy Lemmy Daemon.
Sep 24 13:14:59 metaversum.wtf systemd[1]: lemmy.service: Consumed 6.776s CPU time.
-- Boot 46d9578b9b734c91808a87bb6936b0f0 --
Sep 24 13:18:09 metaversum.wtf systemd[1]: Started lemmy Lemmy Daemon.
Sep 24 13:26:33 metaversum.wtf systemd[1]: Stopping lemmy Lemmy Daemon...
Sep 24 13:27:04 metaversum.wtf systemd[1]: lemmy.service: Succeeded.
Sep 24 13:27:04 metaversum.wtf systemd[1]: Stopped lemmy Lemmy Daemon.
Sep 24 13:27:04 metaversum.wtf systemd[1]: lemmy.service: Consumed 4.280s CPU time.
Sep 24 13:37:32 metaversum.wtf systemd[1]: Started lemmy Lemmy Daemon.
Sep 24 14:02:16 metaversum.wtf systemd[1]: Stopping lemmy Lemmy Daemon...
Sep 24 14:02:46 metaversum.wtf systemd[1]: lemmy.service: Succeeded.
Sep 24 14:02:46 metaversum.wtf systemd[1]: Stopped lemmy Lemmy Daemon.
Sep 24 14:02:46 metaversum.wtf systemd[1]: lemmy.service: Consumed 5.681s CPU time.
Sep 24 14:15:59 metaversum.wtf systemd[1]: Started lemmy Lemmy Daemon.
Sep 24 14:24:12 metaversum.wtf systemd[1]: Stopping lemmy Lemmy Daemon...
Sep 24 14:24:42 metaversum.wtf systemd[1]: lemmy.service: Succeeded.
Sep 24 14:24:42 metaversum.wtf systemd[1]: Stopped lemmy Lemmy Daemon.
Sep 24 14:24:42 metaversum.wtf systemd[1]: lemmy.service: Consumed 2.100s CPU time.


journalctl -feu lemmy-ui
-- Journal begins at Sat 2022-07-30 22:07:20 CEST. --
Sep 24 12:55:56 metaversum.wtf systemd[1]: Started lemmy Lemmy UI Daemon.
Sep 24 13:11:52 metaversum.wtf systemd[1]: Stopping lemmy Lemmy UI Daemon...
Sep 24 13:11:52 metaversum.wtf systemd[1]: lemmy-ui.service: Succeeded.
Sep 24 13:11:52 metaversum.wtf systemd[1]: Stopped lemmy Lemmy UI Daemon.
Sep 24 13:11:52 metaversum.wtf systemd[1]: lemmy-ui.service: Consumed 1.114s CPU time.
Sep 24 13:11:52 metaversum.wtf systemd[1]: Started lemmy Lemmy UI Daemon.
Sep 24 13:14:52 metaversum.wtf systemd[1]: Stopping lemmy Lemmy UI Daemon...
Sep 24 13:14:53 metaversum.wtf systemd[1]: lemmy-ui.service: Succeeded.
Sep 24 13:14:53 metaversum.wtf systemd[1]: Stopped lemmy Lemmy UI Daemon.
-- Boot 46d9578b9b734c91808a87bb6936b0f0 --
Sep 24 13:18:09 metaversum.wtf systemd[1]: Started lemmy Lemmy UI Daemon.
Sep 24 13:27:04 metaversum.wtf systemd[1]: Stopping lemmy Lemmy UI Daemon...
Sep 24 13:27:04 metaversum.wtf systemd[1]: lemmy-ui.service: Succeeded.
Sep 24 13:27:04 metaversum.wtf systemd[1]: Stopped lemmy Lemmy UI Daemon.
Sep 24 13:27:04 metaversum.wtf systemd[1]: lemmy-ui.service: Consumed 1.193s CPU time.
Sep 24 13:37:33 metaversum.wtf systemd[1]: Started lemmy Lemmy UI Daemon.
Sep 24 14:02:46 metaversum.wtf systemd[1]: Stopping lemmy Lemmy UI Daemon...
Sep 24 14:02:46 metaversum.wtf systemd[1]: lemmy-ui.service: Succeeded.
Sep 24 14:02:46 metaversum.wtf systemd[1]: Stopped lemmy Lemmy UI Daemon.
Sep 24 14:21:01 metaversum.wtf systemd[1]: Started lemmy Lemmy UI Daemon.
Sep 24 14:24:43 metaversum.wtf systemd[1]: Stopping lemmy Lemmy UI Daemon...
Sep 24 14:24:43 metaversum.wtf systemd[1]: lemmy-ui.service: Succeeded.
Sep 24 14:24:43 metaversum.wtf systemd[1]: Stopped lemmy Lemmy UI Daemon.


/var/log/lemmy/lemmy.log --> https://paste.metaversum.wtf/?463ef82e03b248ed#tmwsz1qn7ouWpmJRycV5QMzwSSsx7cNkcEaBaFFjdsx

/var/log/lemmy/lemmy-ui.log:
cat /var/log/lemmy/lemmy-ui.log 
Inferno is in development mode.
httpbase: https://127.0.0.1:8536
wsUri: wss://test.metaversum.wtf/api/v3/ws
isHttps: true
No JWT cookie found.
http://0.0.0.0:1235
complete

**Comment by yalh76** [comment]
can you provide the installation logs?

**Comment by Tuxi2020** [comment]
Sure  ;-)
https://paste.yunohost.org/raw/woxucajiva

**Comment by yalh76** [comment]
well after digging, the issue comes from the automatic configuration of new instance
