### ISSUE TITLE
Installation or upgrade from 0.11.3~ynh1 to 0.15.2~ynh3 fails due to missing rust-s3 dependency

### ISSUE THREAD

**Issue by jchammons** [YunoHost-Apps/lemmy_ynh#19]
### Describe the bug

Installing new instance or upgrading from the previous version (0.11.3) to latest 0.15.2 fails with the following error:

```
646737 INFO DEBUG -     Updating crates.io index
646737 INFO DEBUG -     Updating git repository `https://github.com/asonix/rust-s3`
646737 INFO DEBUG - error: failed to get `rust-s3` as a dependency of package `pict-rs v0.3.0-beta.19 (/var/www/build-pict-rs)`
646737 INFO DEBUG -
646737 INFO DEBUG - Caused by:
646737 INFO DEBUG -   failed to load source for dependency `rust-s3`
646737 INFO DEBUG -
646737 INFO DEBUG - Caused by:
646737 INFO DEBUG -   Unable to update https://github.com/asonix/rust-s3?branch=asonix/generic-client#c91e4eca
646737 INFO DEBUG -
646737 INFO DEBUG - Caused by:
646737 INFO DEBUG -   object not found - no match for id (c91e4ecacc8c5a351ff360df68a3cb00863b62bd); class=Odb (9); code=NotFound (-3)
```
### Context

- Hardware: x86_64 server
- YunoHost version: 4.3.6.2
- I have access to my server: SSH, direct, etc.
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: No.
- Using, or trying to install package version/branch: https://github.com/YunoHost-Apps/lemmy_ynh/tree/master
- If upgrading, current package version: 0.11.3~ynh1

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    $ sudo yunohost app install https://github.com/YunoHost-Apps/lemmy_ynh/tree/master --debug
    ```
or
```
$ sudo yunohost app upgrade lemmy -u https://github.com/YunoHost-Apps/lemmy_ynh/tree/master --debug
```

### Expected behavior

Installation or upgrade succeeds. 

### Logs

Full log: https://paste.yunohost.org/raw/nexahidiju

**Comment by jhammons** [comment]
!testme
