### ISSUE TITLE
Upgrade to the latest version

### ISSUE THREAD

**Issue by the7thNightmare** [YunoHost-Apps/lemmy_ynh#34]
### Describe the bug

Lemmy has released a newer version almost one month ago ([announcement](https://join-lemmy.org/news/2023-01-31_-_Lemmy_Release_v0.17.0))

### Context

Lemmy has released v0.17.2, while this YunoHost still in version 0.16.7.

**Comment by mdesmedt** [comment]
Upgrading to 17.2 seems to be a bit problematic with the current setup of lemmy_ynh, as lemmy_ynh seems to be using the default system-wide Postgres package (13.9 on Debian11) while Lemmy 17.2 requires Postgresql 15.

I've been looking at fixing the upgrade script, and it seems like perhaps the right approach here is to migrate the database out of the system-wide Postgresql instance and into the Docker-compose postgres:15-alpine instance. This way the database will be isolated from the rest of the system. But I don't have enough experience with YunoHost and containers to be sure this is wise...

**Comment by ericgaspar** [comment]
IMO it is better to wait for Debian Bookworm support on YunoHost as it will have PostgreSQL 15 as default.

Also I am updating Lemmy to the last commit and moving to YunoHost v2 app package.
https://github.com/YunoHost-Apps/lemmy_ynh/pull/36

No idear as which version is shipping as I cannot test...

**Comment by mdesmedt** [comment]
So Debian Bookworm is here. Would upgrading my server allow me to get the latest version of Lemmy? While running this out of date version I've been encountering quite a few problems, bugs and incompatibilities which are hopefully fixed in the latest upstream.

**Comment by Vardorien** [comment]
> So Debian Bookworm is here. Would upgrading my server allow me to get the latest version of Lemmy? While running this out of date version I've been encountering quite a few problems, bugs and incompatibilities which are hopefully fixed in the latest upstream.

You won't get the newest version of lemmy until an update is pushed to this repo for the app.

**Comment by mdesmedt** [comment]
> You won't get the newest version of lemmy until an update is pushed to this repo for the app.

Yeah I understand. I was ready to experiment with Debian 12 and perhaps make a pull request. But what I didn't expect was YunoHost itself is not Debian 12 ready, for understandable reasons, so it's going to take some time.

The more I use YunoHost the more I wish it was container-based, so application dependencies can be managed outside of the package manager of the server running the YunoHost installation. The current model seems a bit difficult to manage, and restricted to specific Debian/Ubuntu versions to ensure compatibility with applications...

**Comment by mdesmedt** [comment]
> Even if Postgresql 15 comes by default on the new version of debian, it's currently possible to install it anyway, isn't it? Maybe with the way YunoHost works, no?

Yes, you can grab Postgresql 15 for Debian 11 from various places including apt.postgresql.org. However it still seems like a pain, as you would presumably have to set this up specifically for this Lemmy YunoHost installation in order to not introduce conflicts with other potential applications on the server. I can understand why the maintainers of lemmy_ynh might not want to do it...

With Lemmy absolutely exploding in popularity right now it really is unfortunate this version is so far behind. I'm having a lot of problems with incompatibilities between my instance and other more up to date instances, [and the mobile apps I've tried don't support this old version either](https://github.com/mormaer/Mlem/issues/142) :(

**Comment by jahway603** [comment]
Issue https://github.com/YunoHost-Apps/lemmy_ynh/issues/58 requires this Issue to be resolved.

**Comment by jahway603** [comment]
[Lemmy.world was recently hacked & defaced by a serious cross-site scripting vulnerability](https://lemdit.com/post/44994). How many Yunohost instances will be hacked before this module is upgraded to the latest version?
