### ISSUE TITLE
Unable to link lemmy instance to other lemmy instances

### ISSUE THREAD

**Issue by jahway603** [YunoHost-Apps/lemmy_ynh#40]
### Describe the bug

There is no documentation or menu item to link my lemmy_ynh instance to other lemmy instances

### Context

- Hardware: VM
- YunoHost version: 11.1.20
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
  - If yes, please explain:
- Using, or trying to install package version/branch: lemmy_ynh 0.16.7~ynh1
- If upgrading, current package version: N/A

### Steps to reproduce

1. Try to link lemmy_ynh instance to other instances.
2. No menu GUI items exist to do this.
3. No documentation exists to do this.

### Expected behavior

Be able to link my lemmy_ynh instance to other Lemmy instances since it's a federated service using ActivityPub protocol.

### Logs

N/A

### Other information

Upstream describes how to do this here, https://join-lemmy.org/docs/en/administration/federation_getting_started.html, but it's not working with the yunohost implementation.

**Comment by mdesmedt** [comment]
Did you paste an URL such as https://beehaw.org/c/technology in the search box of your instance and it did not work? Because that's how you're supposed to view communities in other instances. Then you need to subscribe to them before you start getting a feed of posts/comments.

**Comment by jahway603** [comment]
That worked. Thank you @mdesmedt
