### ISSUE TITLE
Can't see Lemmy once it's installed. 

### ISSUE THREAD

**Issue by VOGUK** [YunoHost-Apps/lemmy_ynh#44]
Hardware: Thinkpad Laptop – Intel i5 – 4GB RAM
YunoHost version: Latest ISO – fresh install
I have access to my server : SSH & Web Admin
Are you in a special context or did you perform some particular tweaking on your YunoHost instance ? : No
If yes, please explain:

Description of my issue:
When I make a fresh installation of Lemmy, it installs correctly with no error messages. However, when I go to the app list, it's there, but on the user side there is no tile and when I go the subdomain I have created, nothing loads and nothing appears to be there. Am I doing something wrong? :/

**Comment by tituspijean** [comment]
Give yourself permission to access the app, in the webadmin.

**Comment by csolisr** [comment]
Found the same issue, would be nice to have the default permissions set by the installer itself as in most other YNH apps.

**Comment by VOGUK** [comment]
Can I ask how you give the permission in the webadmin?

**Comment by csolisr** [comment]
- Go to https://yourwebsite.example.net/yunohost/admin/
- Go to Applications => Lemmy (or whatever other app)
- On the section "Groups / users currently allowed to access this app:" there will be a button called "Manage groups and permissions", click that
- Go to the "Visitors" section (as this needs to be public to federate), click on "Add a permission" and select "Lemmy" (or your app) from the dropdown list

**Comment by VOGUK** [comment]
Awesome, that worked, thank you so much! :)

**Comment by ericgaspar** [comment]
Fixed with #49
