### ISSUE TITLE
Release 0.18.1 fixes a cross-site scripting vulnerability

### ISSUE THREAD

**Issue by jahway603** [YunoHost-Apps/lemmy_ynh#58]
Release 0.18.1 fixes a cross-site scripting vulnerability
https://github.com/LemmyNet/lemmy/releases/tag/0.18.1

"Additionally this version includes a fix for another cross-site scripting vulnerability. For these reasons instance admins should upgrade as soon as possible." -- https://lemmy.ml/post/1808829

**Comment by jahway603** [comment]
Related to Issue https://github.com/YunoHost-Apps/lemmy_ynh/issues/34

**Comment by jahway603** [comment]
[Lemmy.world was hacking by this serious vulnerability](https://lemdit.com/post/44994). How many Yunohost instances will be hacked before this is worked on & fixed?

**Comment by ericgaspar** [comment]
As you can see, #50 failed and I don't know how to fix this...
