### ISSUE TITLE
Lemmy 0.19.1

### ISSUE THREAD

**Issue by LucifersCircle** [YunoHost-Apps/lemmy_ynh#79]
Hello, running into issues with version 0.18.2 and was wondering if it’s possible to update to the newer 0.19.1? Thanks for your efforts put into this yunohost package!

https://github.com/LemmyNet/lemmy/releases/tag/0.19.1

**Comment by ericgaspar** [comment]
thank you for the reminding. Please feel free to contribute to the testing version (v0.19.3): https://github.com/YunoHost-Apps/lemmy_ynh/pull/86
