### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by Lezney** [YunoHost-Apps/lemmy_ynh#88]
Currently this is on version 0.18.2. While I don't see 0.18.2 on the official Lemmy repository, 0.18.3 was released nearly a year ago. I'd say this repository is overdue for an update.

![image](https://github.com/YunoHost-Apps/lemmy_ynh/assets/149842068/d1b397f6-c7f6-4783-a522-e57581286a47)

We need at least 0.19.0 to get access to third party tools like Voyager and Photon

![image](https://github.com/YunoHost-Apps/lemmy_ynh/assets/149842068/0e73f3d5-a2ae-444e-9b76-7549fb5e7f61)

Thank you for your consideration.

**Comment by ericgaspar** [comment]
thank you for the reminding. Please feel free to contribute to the testing version (v0.19.3): https://github.com/YunoHost-Apps/lemmy_ynh/pull/86

**Comment by Lezney** [comment]
> thank you for the reminding. Please feel free to contribute to the testing version (v0.19.3): #86

What? What am I contributing? It wasn't updated. Is there some sort of technical issue? Why is this issue closed? I have no idea what just happened.
